//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_WebServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWCFInterface")]
    public interface IWCFInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/ShowOut", ReplyAction="http://tempuri.org/IWCFInterface/ShowOutResponse")]
        bool ShowOut(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWCFInterfaceChannel : WCF_WebServiceClient.ServiceReference1.IWCFInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFInterfaceClient : System.ServiceModel.ClientBase<WCF_WebServiceClient.ServiceReference1.IWCFInterface>, WCF_WebServiceClient.ServiceReference1.IWCFInterface {
        
        public WCFInterfaceClient() {
        }
        
        public WCFInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ShowOut(string str) {
            return base.Channel.ShowOut(str);
        }
    }
}
